### PR TITLE
Refactor context

### PR DESCRIPTION
**Pull request by granawkins**
This is a small PR building on #86 which moves the CodeMap and DiffContext from `code_file_manager` to `code_context`. 

The next steps (in separate PRs) will be
- Refactor CodeFile to handle read/write ops
- Streamline the context-generating process inside CodeContext
- Add Embeddings

### CODE REVIEW

**Comment by jakethekoenig** [comment]
Seems like mentat always has similar suggestions. I like the summary.
```
(.venv) Development/mentat % mentat --pr-diff main mentat/diff_context.py mentat/git_handler.py
Files included in context:
mentat
└── mentat
    ├── diff_context.py
    └── git_handler.py

Diff annotations:
 ─•─ Merge-base Branch main: 1907a988: Exercism Benchmark (#92) | 10 files | 519 lines


Including CodeMap (filepaths only)
File and prompt token count: 7084 / 8192
Type 'q' or use Ctrl-C to quit at any time.

What can I do for you?
>>> I'd like some help reviewing this pull request. Can you describe its function and point
out anything you think could be improved?

Including CodeMap (filepaths only)

Total token count: 7109

streaming...  use control-c to interrupt the model at any point

This pull request adds functionality to handle and display diffs in the context of code changes. The main changes are in `mentat/diff_context.py` and `mentat/git_handler.py`.

In `mentat/diff_context.py`, a new class `DiffAnnotation` is added to represent an annotation in a diff. The functions `_parse_diff`, `_annotate_file_message`, and `annotate_file_message` are used to parse and annotate the diff. The `DiffContext` class is updated to handle the new functionality.

In `mentat/git_handler.py`, new functions `get_diff_for_file`, `get_treeish_metadata`, `get_files_in_diff`, `check_head_exists`, and `get_default_branch` are added to handle various Git operations related to diffs.

The changes seem to be well-structured and modular. However, there are a few points that could be improved:

1. Add docstrings to the new functions and classes to provide a clear explanation of their purpose and usage.
2. In `_parse_diff` function, it might be helpful to add comments explaining the logic behind parsing the diff lines.
3. In `_annotate_file_message` function, it might be helpful to add comments explaining the logic behind annotating the file message with the diff annotations.
4. Consider adding more error handling and logging in case of unexpected input or issues with Git commands.
Speed: 8.97 tkns/s | Cost: $0.23
```

**Comment by jakethekoenig** [comment]
Ah I guess `mentat --diff main` is what I want since your last pr hasn't been merged

**Review by jakethekoenig — APPROVED** [review]
Moving that logic out of conversation and app make a lot of sense to me. Thanks!

**Review by PCSwingle — APPROVED** [review]
All looks great to me!

**Review by biobootloader — APPROVED** [review]
Thanks @granawkins!

And thanks @PCSwingle for fixing merge conflicts

**Pull request merged**
